### ISSUE TITLE
Suggestion for better scientific notation format

### ISSUE THREAD

**Issue by gbaraldi** [PaddiM8/kalker#51]
Just the title. I tried to look around and couldn't find if it is possible or, if it is, how to do it.

**Comment by PaddiM8** [comment]
You mean like `2.56*10^2`?

**Comment by gbaraldi** [comment]
I was thinking about 2.56E2 or something similar since it gets easier to read when used in more complicated expressions. I'm not sure if is easy to support but just a suggestion.

**Comment by sergeevabc** [comment]
Whatever you add in the future, please let the output remain standard without extra switches where possible.
It is a challenge to find an intuitive one-file terminal calc for Windows with percentages support besides [Qalc][1].
And, by the way, consider replacing MSI package with ZIP, since only one file is involved.

[1]: https://qalculate.github.io/

**Comment by PaddiM8** [comment]
Hm, not worth the added ambiguity right now.
