### ISSUE TITLE
Unexpected variable copy behavior

### ISSUE THREAD

**Issue by brandondong** [PaddiM8/kalker#59]
![image](https://user-images.githubusercontent.com/13722457/134260220-a8910dd5-1a01-42b1-918a-d0b32bfcdeeb.png)

For such a tool, I would expect the `y = x` line to assign `y` the value of `x` and subsequently for the two variables to be completely independent of each other.

**Comment by PaddiM8** [comment]
Hmm, I'm a bit uncertain about this. On one hand, it makes sense that you may just want to use the _current_ value, but on the other hand, if you define that `y` is equal to `x`, you may want that to continue to be the case. I guess you don't go around changing values like this in maths though, so I'm not certain what the best thing would be. The way it works now is probably the easiest implementation-wise, since functions like `sum` mutate a variable to get different results in different iterations.

I'm not a mathematician though, so I'll see if I can get some input from some.

**Comment by PaddiM8** [comment]
I have decided to not change this behaviour.
