### ISSUE TITLE
Wrong comparing with expressions

### ISSUE THREAD

**Issue by Dartt0n** [PaddiM8/kalker#65]
I found this while using the program.
The program incorrectly compares an expression with a trigonometric function and a number.
```
>> 3 * 4 * cos(60deg)
6
>> 3 * 4 * cos(60deg) <= 6
false
>> 3 * 4 * cos(60deg) > 6
true
>> 6 <= 6
true
>> 6 > 6
false
```
The 2nd and 3rd expressions are incorrect.

**Comment by PaddiM8** [comment]
Ah yes. The problem seems to have been that comparisons are done too aggressively. Sometimes obviously you can't get exact numerical answers, which meant these tiny tiny differences (that normally get rounded appropriately before actually being displayed) would not be evaluated as being equal. This should now be fixed.
