### ISSUE TITLE
some strange var behaviour

### ISSUE THREAD

**Issue by adsick** [PaddiM8/kalker#83]
look at this:
![image](https://user-images.githubusercontent.com/24528839/143764567-bb04e45d-f35d-47a7-9f99-f12232e8494a.png)

h is just equals to 1 when it should be 5762.37

**Comment by PaddiM8** [comment]
This is because variables are reference expressions rather than containing copies of values. When a variable is redefined, other variables containing the redefined one will start showing another value. This behaviour makes sense in most cases, but in this case (with `ans`) it makes less sense. However, it might be confusing to have a different behaviour specifically for `ans`, and probably wouldn't be very clean to implement either.

**Comment by PaddiM8** [comment]
Variable copy/reference behaviour is tracked in issue #59.
